-- INSERT INTO admin (admin_id, username, password, name, lastname) 
-- VALUES(
--   1,
--   "Admin", 
--   "Admin!", 
--   "Giannhs", 
--   "Papadopoulos", 
-- );

-- INSERT INTO rescuer (resc_id, username, password, name, lastname, r_cords, car_name) 
-- VALUES(
--   2,
--   "rescuer1",
--   "rescuer1!",
--   "Mixalhs",
--   "Giannakopoulos",
--   POINT(38.246229, 21.735412),
--   "Oxhma_1"
-- );

-- INSERT INTO citizen (citizen_id, username, password, name, lastname, phone, email, address, zip, c_cords) 
-- VALUES(
--   3,
--   "citizen1",
--   "citizen1!",
--   "Petros",
--   "Dhmiakos",
--   "6911111111",
--   "petrosdhmiakos@gmail.com",
--   "Pantanashs",
--   10
-- );